## Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

customization_mobile_client_enabled: '${customization.mobile.enabled}'

qt_directory: '${QT_DIR}'

distribution_output_dir: '${distribution_output_dir}'

# Source directories
bin_source_dir: '${bin_source_dir}'
current_binary_dir: '${CMAKE_CURRENT_BINARY_DIR}'
cmake_binary_dir: '${CMAKE_BINARY_DIR}'
ucrt_directory: '${ucrt_directory}'
vcrt_directory: '${vcrt_directory}'
client_qml_dir: '${client_qml_directory}'
help_directory: '${help_directory}'
fonts_directory: '${CMAKE_BINARY_DIR}/bin/fonts'
client_update_files_directory: '${client_update_files_directory}'
server_update_files_directory: '${server_update_files_directory}'
mobile_help_source_file_path: '${mobile_help_directory}/${mobile_help_file_name}'
mobile_help_destination_file_name: '${mobile_help_file_name}'
quick_start_guide_source_file_path: '${quick_start_guide_directory}/${quick_start_guide_file_name}'
quick_start_guide_destination_file_name: '${quick_start_guide_file_name}'

# Source binaries
client_binary_name: '${client.binary.name}'
minilauncher_binary_name: '${minilauncher.binary.name}'
launcher_version_file: '${launcher.version.file}'

# ASan required library
asan_library_name: '${asan_library_name}'

# List of translation packages
client_translation_files: '${client_translation_files}'
