arch: '${arch}'
wix_directory: '${wix_directory}/bin'
qt_directory: '${qt.dir}'
build_configuration: '${build.configuration}'
installer_cultures: '${installer.cultures}'
installer_language: '${installer.language}'
distribution_output_dir: '${distribution_output_dir}'

# Source directories
bin_source_dir: '${bin_source_dir}'
vox_source_dir: '${VoxSourceDir}'
vcredist_directory: '${vcredist_directory}'
client_qml_dir: '${client_qml_dir}'
help_directory: '${help_directory}'
festival_vox_directory: '${festival_vox_directory}'
fonts_directory: '${fonts_directory}'

# Source binaries
client_binary_name: '${product.name}'
minilauncher_binary_name: '${minilauncher.binary.name}'
launcher_version_file: '${launcher.version.file}'

# Signing section
signtool_directory: '${signtool_directory}/bin'
main_certificate: '${certificates_path}/wixsetup/${sign.cer}'
additional_certificate: '${sign.intermediate.cer}'
sign_password: '${sign.password}'
sign_description: '${company.name} ${display.product.name}'

# Distrib names
client_distribution_name: '${client_distribution_name}'
server_distribution_name: '${server_distribution_name}'
bundle_distribution_name: '${bundle_distribution_name}'
servertool_distribution_name: '${servertool_distribution_name}'
paxton_distribution_name: '${paxton_distribution_name}'
